version: '3.8'

services:
  wiremock-service:
    image: rodolpheche/wiremock
    container_name: wiremock-service
    ports:
      - "8822:8080"
    volumes:
      - ./wiremock/stubs/__files/:/home/wiremock/__files/
      - ./wiremock/stubs/mappings/:/home/wiremock/mappings/
    command:
      - -verbose
      - -global-response-templating